### PR TITLE
Implementation of InMemory feature for post manipulation of retrieved data.

### PR DESCRIPTION
**Pull request by fiseni**
Now that other PRs are merged, this is one more feature that is mentioned in #50
It's quite straightforward, the specification holds `Func<List<T>, List<T>>` predicate, and this is callled after the data is retrieved from persistence.
The usage is as following:

```
public class CompanySpec : Specification<Company>
{
    public CompanySpec(int countryId)
    {
        Query.Where(x => x.CountryId == countryId)
             .Include(x => x.Stores);

        Query.InMemory(x =>
        {
            // Here you are not constrained to the specification builder.
            // You can use everything that .NET offers in order to manipulate List
        });
    }
}
```

I must admit, at first glance this seemed quite appealing feature, but I'm having second thoughts on that :)
Not a bad thing to have it, but if thought carefully very rarerly will be used. If you're in a position that you need additional filtering after the DB query is completed, then it means you have quite inefficient query.
One use case, since `IncludeWhere` is not supported until EF Core 5, then you might need additionally filtering based on some complex conditions on the navigations? Maybe?

I don't know, the community might find some other use cases.

### CODE REVIEW

**Comment by fiseni** [comment]
As soon I wrote the previous comment, an apple fall on my head :)

If you love domain events and use them often in your code, then most probably you always have trouble to decide where exactly to subscribe to them? Imagine the aggregate root have to subscribe to its child's event. Now you can just iterate through the collection and call subscribe for each retrieved aggregate root. As a final result, you get list of aggregates from repository who are already completely set.

Note: This is actually more valid if you're using .NET events. If you have your own event aggregator or similar infrastructure, then there are other ways to this problem.

**Comment by fiseni** [comment]
If we're ok with the naming, this can be merged too (resolved the conflicts now).

**Comment by wrakocy** [comment]
Hi @fiseni . Wondering if the InMemory feature was ever released? I'm pulling in version 5.1, but not seeing it. Thanks!

**Comment by fiseni** [comment]
Yes, it's there, but renamed to `PostProcessingAction`.
We did that to avoid confusion with in-memory evaluators in version 5.

Sorry, we have not been very careful in documenting all changes. We're working on the documentation.

**Comment by wrakocy** [comment]
Ah! OK, perfect. That'll do just fine ;) Thanks for the assist!

**Pull request merged**
