### PR TITLE
Add `AddRangeAsnyc` to specification repository base and ef6/efcore repositories

### PR DESCRIPTION
**Pull request by MarkusGnigler**
Related to #234

### CODE REVIEW

**Comment by fiseni** [comment]
Hey @MarkusGnigler,

Would you mind resolving the merge conflicts? It seems you're not working on the last state of the main branch.

**Comment by MarkusGnigler** [comment]
Hy @fiseni ,

oh sry it's my bad, i merged the main branch today and thought i was on the current state. 
I'll merge the conflicts.

**Review by fiseni — APPROVED** [review]

**Comment by fiseni** [comment]
Thanks @MarkusGnigler

**Comment by fiseni** [comment]
Closes #234

**Comment by MarkusGnigler** [comment]
@fiseni 

Would also test the method, but unfortunately have an error in vs with the path of a .editorconfig in the core project. 
Do you have any suggestion for me?

> VS2019
image

> VS2020
image

**Comment by fiseni** [comment]
Perhaps you should do a dotnet clean, delete the obj folders manually if necessary. Something got messed up locally.
Ensure that your fork is up to date and that you actually have the editorconfig file in the repository root.

**Comment by MarkusGnigler** [comment]
It was a problem with long paths as it suggested in the error message.
In windows i enable long paths in powershell with:

[Doc](https://docs.microsoft.com/en-us/windows/win32/fileio/maximum-file-path-limitation?tabs=powershell)

```ps1
New-ItemProperty -Path "HKLM:\SYSTEM\CurrentControlSet\Control\FileSystem" `
    -Name "LongPathsEnabled" -Value 1 -PropertyType DWORD -Force
```

**Comment by snax4a** [comment]
Hi, when do you plan to release this feature?
I see that v6.0.1 does not have it.

**Comment by olesakn** [comment]
I am also waiting on this feature. Would love to see it get included in the next release.

**Pull request merged**
